export const WORK_HISTORY_REQUEST = 'WORK_HISTORY_REQUEST'
export const WORK_HISTORY_REQUEST_SUCCESS = 'WORK_HISTORY_REQUEST_SUCCESS'
export const WORK_HISTORY_REQUEST_FAILURE = 'WORK_HISTORY_REQUEST_FAILURE'
